#token: #?? ?? ?? ??
#  access_token:
#    expiration_time: 86400000 #??
#  refresh_token:
#    expiration_time: 604800000 #30?
#    expiration_date: 30
#  secret: secret

spring:
  profiles:
    active: local

---
spring:
  profiles:
    active: dev