logging:
  file:
    name: ${user.dir}/logs/${spring.application.name}.log
  level: # ? ????? ?? ?? ??
    org.jjinppang.jjinppang: ERROR
    org.jjinppang.jjinppang.controller: DEBUG
    org.hibernate.sql: DEBUG
  logback:
    rolling policy:
      max-history: 7 # ???? ?? ?? 7?
      max-file-size: 10MB # ???? ??? ?? ??


token: #?? ?? ?? ??
  access_token:
    expiration_time: 86400000 #??
  refresh_token:
    expiration_time: 604800000 #30?
    expiration_date: 30
  secret: secret

spring:
  application:
    name: jjinppang

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jjinppang?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '!@qwasqw12'
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      #update -> ???????? #none -> ????(????)
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: false
        default_batch_fetch_size: 100
    open-in-view: false

